version: '3.8'
services:
  db:
    image: postgres:16
    container_name: subscriptionanalytics-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: subscriptionanalytics_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: 